import { app, BrowserWindow, ipcMain, dialog, protocol } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import * as isDev from 'electron-is-dev';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

// Create custom protocol
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'local-file',
    privileges: {
      standard: true,
      supportFetchAPI: true,
      corsEnabled: true,
      secure: true,
      bypassCSP: true,
    },
  },
]);

const createWindow = (): void => {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: true,
    },
  });

  const startUrl = MAIN_WINDOW_WEBPACK_ENTRY;

  mainWindow.loadURL(startUrl);

  if (isDev) {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

// Register protocol for serving local files securely
app.whenReady().then(() => {
  protocol.registerFileProtocol('local-file', (request, callback) => {
    const url = request.url.replace('local-file://', '');
    try {
      return callback(decodeURI(url));
    } catch (error) {
      console.error(error);
      return callback('404');
    }
  });
});

app.on('ready', createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// File handling - Open WAV file
ipcMain.handle('open-wav-file', async () => {
  if (!mainWindow) return { canceled: true };
  
  const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
    properties: ['openFile'],
    filters: [{ name: 'Audio', extensions: ['wav'] }],
  });
  
  if (canceled || filePaths.length === 0) {
    return { canceled: true };
  }
  
  const filePath = filePaths[0];
  
  try {
    // Read file as buffer
    const buffer = fs.readFileSync(filePath);
    
    // Return file details
    return {
      canceled: false,
      filePath,
      fileName: path.basename(filePath),
      buffer: buffer.buffer,
    };
  } catch (error) {
    console.error('Error reading WAV file:', error);
    return { canceled: true, error: (error as Error).message };
  }
});

// File handling - Open Media files (images/videos)
ipcMain.handle('open-media-files', async () => {
  if (!mainWindow) return { canceled: true };
  
  const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
    properties: ['openFile', 'multiSelections'],
    filters: [
      { name: 'Media', extensions: ['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'ogg'] }
    ],
  });
  
  if (canceled || filePaths.length === 0) {
    return { canceled: true };
  }
  
  try {
    // Process each file
    const mediaFiles = filePaths.map(filePath => {
      // Use our custom protocol for secure local file access
      return {
        filePath,
        fileName: path.basename(filePath),
        url: `local-file://${filePath}` // Use custom protocol instead of file://
      };
    });
    
    // Return media files details
    return {
      canceled: false,
      mediaFiles
    };
  } catch (error) {
    console.error('Error processing media files:', error);
    return { canceled: true, error: (error as Error).message };
  }
});